BITS32 = 32
BITS31 = 31

SIGN_BITS = 1
EXP_BITS = 8
MANTISSA_BITS = 23

EXP_BIAS = 127

EXP_START = 1
EXP_END = EXP_START + EXP_BITS
MANTISSA_START = EXP_END

MAX_EXP = (1 << EXP_BITS) - 1

MANTISSA_FULL = MANTISSA_BITS + 1      
MANTISSA_EXTENDED = MANTISSA_BITS + 2 

FRAC_BITS = 20

BCD_BITS = 4
BCD_BASE = 10
BCD_CORRECTION = 6
BCD_MAX = 16